on:
  issues:
    types:
      - labeled
jobs:
  transfer_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Transfer Issue & Create Stub
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.SECRET_TOKEN }}
        router: Confirmed:dimension-delvers-mod
        create_stub: true
